### ISSUE TITLE
Message don't update and can't stop Server

### ISSUE THREAD

**Issue by martinussuijkerbuijk** [maybites/blender.NodeOSC#1]
Hello,

When I send an osc message only the first message comes true, and after that the messages are not updated. Also when I close the server it can't stop the server and it throws this error message:

PyLiblo Server sended test message to 127.0.0.1 on port 9002
PyLiblo Server starting up....
... server started 5005
Traceback (most recent call last):
  File "C:\Users\martinus\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\NodeOSC\server\callbacks.py", line 51, in execute_queued_OSC_callbacks
    executeAnimationNodeTrees()
  File "C:\Users\martinus\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\NodeOSC\nodes\nodes.py", line 111, in executeAnimationNodeTrees
    propertyChanged()
NameError: name 'propertyChanged' is not defined
Info: Server stopped!

Traceback (most recent call last):
  File "C:\Users\martinus\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\NodeOSC\server\_base.py", line 106, in modal
    return self.cancel(context)
  File "C:\Users\martinus\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\NodeOSC\server\_base.py", line 249, in cancel
    bpy.app.timers.unregister(execute_queued_OSC_callbacks)
ValueError: Error: function is not registered

location: <unknown location>:-1

location: <unknown location>:-1

I've reinstalled Blender, but error persists. Any ideas how to solve this?

**Comment by maybites** [comment]
I assume you try to play with Animation Nodes. Which version do you use?

**Comment by martinussuijkerbuijk** [comment]
No actually I needed it for a much simpler pupose and solved it with just using socket. Great plugin though.

**Comment by maybites** [comment]
not great enough when it is not working for you. I pushed a fix to the development branch, though. but since you are not using AN, I don't understand how the code could actually reach that line.
