### ISSUE TITLE
Blender Python mismatch error blender 3.3.1 

### ISSUE THREAD

**Issue by bigandtallrecords** [maybites/blender.NodeOSC#27]
Getting this traceback: 
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\NodeOSC\__init__.py", line 61, in <module>
    from .server import server, operators
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\NodeOSC\server\server.py", line 34, in <module>
    from ._base import *
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\NodeOSC\server\_base.py", line 13, in <module>
    from .callbacks import *
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\NodeOSC\server\callbacks.py", line 4, in <module>
    from ..nodes.nodes import *
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\NodeOSC\nodes\nodes.py", line 16, in <module>
    from animation_nodes.events import propertyChanged
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\animation_nodes\__init__.py", line 137, in <module>
    raise Exception(message)
Exception: 

There is a Python version mismatch.

Your Blender build uses: (3, 10, 2)
Animation Nodes has been compiled for: (3, 9, 7)

You have three options:
  1. Try to make Blender use another Python version.
     (Blender 2.93 officially uses Python 3.9.x)
  2. Compile Animation Nodes yourself using the correct Python version.
     (Look in the developer manual for more information)
  3. Create an issue on Github and ask if someone can create a build for you.

**Comment by bigandtallrecords** [comment]
Figured it out. If animation nodes was installed it throws this error. Be sure to remove old animations nodes plugin before activating.
